version: '3.8'

services:
  mock-gps-api:
    build: .
    ports:
      - "5001:5001"  # Bind to all interfaces (we'll use UFW to restrict)
    volumes:
      - ./route.gpx:/app/route.gpx:ro  # Read-only mount
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - GPS_API_KEY=${GPS_API_KEY:-your-secret-api-key-change-this}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-127.0.0.1,localhost}
    env_file:
      - .env
    networks:
      - gps-api-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/user_location"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  gps-api-network:
    driver: bridge 