apiVersion: v1
kind: Secret
metadata:
  name: gps-api-secrets
  namespace: mock-gps-api
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  GPS_API_KEY: <base64-encoded-api-key>
  ALLOWED_HOSTS: <base64-encoded-allowed-hosts>
